### ISSUE TITLE
Intermittent promis failure bug in Block Explorer

### ISSUE THREAD

**Issue by johnmcdowall** [trufflesuite/zircon#13]
Only happens occasionally, and while generating the first few blocks

**Comment by johnmcdowall** [comment]
Here's the exception: 

```
Uncaught Exception:
TypeError: Cannot read property 'get' of undefined
    at dbGet (/Users/jmd/code/clients/consensys/zircon/node_modules/merkle-patricia-tree/baseTrie.js:151:7)
    at /Users/jmd/code/clients/consensys/zircon/node_modules/merkle-patricia-tree/util.js:66:5
    at /Users/jmd/code/clients/consensys/zircon/node_modules/async/lib/async.js:181:20
    at iterate (/Users/jmd/code/clients/consensys/zircon/node_modules/async/lib/async.js:262:13)
    at /Users/jmd/code/clients/consensys/zircon/node_modules/async/lib/async.js:274:29
    at /Users/jmd/code/clients/consensys/zircon/node_modules/async/lib/async.js:44:16
    at /Users/jmd/code/clients/consensys/zircon/node_modules/merkle-patricia-tree/util.js:71:7
    at /Users/jmd/code/clients/consensys/zircon/node_modules/merkle-patricia-tree/baseTrie.js:156:9
    at dispatchError (/Users/jmd/code/clients/consensys/zircon/node_modules/levelup/lib/util.js:64:35)
    at /Users/jmd/code/clients/consensys/zircon/node_modules/levelup/lib/levelup.js:222:14
```
